name: magento2
type: magento2
docroot: pub
php_version: "8.5"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mariadb
    version: "11.4"
upload_dirs:
    - media
use_dns_when_possible: true
composer_version: "2"
disable_settings_management: true
web_environment: []
corepack_enable: false
